### PR TITLE
SQS convention change and monitoring implementation

### PR DESCRIPTION
**Pull request by jamesdotcom**
@thabofletcher I'd appreciate it if you could review this branch when you get a chance. Thanks

### CODE REVIEW

**Comment by thabofletcher** [comment]
Hey @jamesdotcom, sorry it took me a little bit to get to this. It looks like mostly this is an extension of the library, which is conceptually a good direction, the event models stuff and the queue monitoring.

My concerns
1. In the README.md, the way the verbage has changed, its unclear that the library takes care of the SNS/SQS abstraction. From it's design I believe the library is largely useful in its ability to do that abstraction, so consumers should not be creating SNS topics or listening to SQS queues or they will tie us to the underlying implementation. I would restore the Publisher() Subscriber() example to show off how it is used, then perhaps go into the EventPublisher() and how it is used.
2. The EventPublisher() class is not an abstraction of the Publisher() class and doesnt reuse any existing code. You could say EventPublisher extends Publisher, but theoretically a Publisher shouldn't be publishing in a different way, the model that is being published is what primarily matters to both endpoints. Another way of putting it is the publish/subscribe functions are a transport, and the event is schema, so the transport layer should avoid being schema specific. If it must be schema specific, then it should reuse the existing code and extend it.

**Comment by jamesdotcom** [comment]
Thanks for the feedback. The Publisher and Subscriber classes are obsolete
with this implementation so that may be where some confusion comes in. That
is why the Publisher/Subscriber information is not in the readme. If you
are ok with it, I'll remove them so there's no confusion about which
classes to use.

The examples then can be improved to provide a full class implementation
like you had before. I'll work on making those examples clearer. I'll also
modify the text to make it clearer that the SNS/SQS steps are prerequisite
configuration and that all runtime usage of SNS/SQS is provided by the
library.

**Comment by thabofletcher** [comment]
Unfortunately, I had designed those specifically to be loosely typed. You designed the event architecture following to be strongly typed, which I respectfully disagree about. Inevitably the schema will need to iterate over time with the needs of applications, so maintaining that here seems like just making work for ourselves - instead of implementing change solely on the endpoints, we may additionally need to change the event lib and the endpoints, as well as redeploy the event lib out to all the clients so they are up on the new event schema. 

That decision obviously has already been made, however I still see no reason for a rigid schema to be enforced at the transport layer - if you build it on top of the abstractions that are already there then you have the options of both and you can decide per application what is the right tool for the job (maybe you want to use the same publish/subscribe model but not for events).

**Comment by jamesdotcom** [comment]
I don't see it as enforcing a rigid schema at all. There is a common
payload to structure the metadata of the event. The content itself is just
a json string so it can be whatever you want it to be and can change as
necessary without any changes to the library.

I don't understand your comments about changing the endpoints. I have
revved the version of the library so you can continue to use the version
you have without modification.

**Comment by jamesdotcom** [comment]
I will use the analogy that the event payload is like a standard shipping
box. The sender can put whatever they want in box. If the sender wants to
change the contents, it can do so without needing to change the box or the
shipping method itself.

**Comment by thabofletcher** [comment]
So using your analogy, we basically are introducing complexity only to obsolete a transport mechanism that can handle any type of box, to one that can only handle this type of box. The decision to standardize on a shipping box is fine, there just isn't a reason to modify the original publishing/subscription mechanism.

Rather than obsoleting existing classes for something less flexible, I'm asking you to consider inheriting from the existing classes and extending their functionality rather than locking us  into a less flexible model. We could also have message metadata by taking off raw message delivery and use/extend the perfectly good metadata AWS already provides, but the intention of the original library was to provide a transport mechanism that was payload agnostic.

I'm not asking you to change your design, I'm asking you to implement using standard OO so the design qualities we both value are present.

**Comment by jamesdotcom** [comment]
I think we'll just have to agree to disagree at this point. I'll just
create a separate library. I really don't understand your complexity
argument so I think the design approaches are not compatible. As far as
using the AWS metadata, we are trying to hide that because we may use
something else besides SNS/SQS in the future. Also, the metadata I'm
referring to is metadata like user id and source object id. That won't be
provided by AWS.

**Comment by thabofletcher** [comment]
I guess that makes sense. You aren't really modifying any of the existing code anyway, so if you want to just use the library as a reference and make something else thats fine. I think there is a way code wise to share the underlying SNS/SQS transport, but if you disagree, then do your thing.

**Pull request closed without merging**
